### ISSUE TITLE
trying to come up with a MWE for analysis

### ISSUE THREAD

**Issue by andrewkern** [andrewkern/analysis#1]
Hey @jeromekelleher @petrelharp @arundurvasula- check out this minimal working example I've put together for doing $N(t)$ estimation using `stairwayplot` and `snakemake`. I'd love to get your comments on it and then can get it into better shape before a PR

**Comment by andrewkern** [comment]
I should mention where this MWE is of course. You can find it [here](https://github.com/andrewkern/analysis/tree/master/n_t) on my fork of `analysis `

**Comment by andrewkern** [comment]
@agladstein I'd love your feedback on this sketch here if possible. let me know what works and what doesn't

**Comment by jeromekelleher** [comment]
Looks totally excellent @andrewkern, I think it's a great way to lay things out.

One thing though: do we want to bundle the stairway plot into the repo? I would have thought we'd treat this as an external dependency that we install into the environment somehow (or pull into a top-level 'tools' directory or something). The way I approach this sort of thing usually is to have a directory within the repo for tools like this with a Makefile. The Makefile will then download/compile/whatever is needed to make it useable.

**Comment by andrewkern** [comment]
yep. I included it because download was non-standard, but can make a tarball and put the tarball on my server here at UO. Any complaints if I stick with using `snakemake` rather than GNU `make` for download/compilation? I'm enjoying learning about `snakemake`

**Comment by jeromekelleher** [comment]
> yep. I included it because download was non-standard, but can make a tarball and put the tarball on my server here at UO. Any complaints if I stick with using snakemake rather than GNU make for download/compilation? I'm enjoying learning about snakemake

Ah, makes sense. No objections to snakemake, whatever's easiest.

**Comment by arundurvasula** [comment]
Nice Andy! I had a similar question regarding the stairway plot download -- but it looks like it comes from Google drive so we're gonna have to include it ourselves which I think is ok. 

I was wondering if we want to specify some sort of output that's easy to look at? E.g. should the end result be a notebook or a collection of plots? Or is this part of the analysis that's going to be main figures in the paper?

**Comment by andrewkern** [comment]
closing this old issue.
