### ISSUE TITLE
parallezation

### ISSUE THREAD

**Issue by agladstein** [andrewkern/analysis#3]
Speaking of farming out to cluster nodes...

Can snakemake take care of that? Like, can snakemake submit dependent jobs to a cluster?

I'm a little bit more familiar with makeflow, but haven't really used it. I'm pretty sure makeflow is HPC/cloud compatible.

**Comment by andrewkern** [comment]
yup: https://snakemake.readthedocs.io/en/stable/executable.html#cluster-execution

I haven't done it yet though. This is the first project I've bothered to use `snakemake` on.

**Comment by agladstein** [comment]
Nice! Ok. Worth playing with.
