### ISSUE TITLE
how to run??

### ISSUE THREAD

**Issue by agladstein** [andrewkern/analysis#4]
So... 
README says

The basic workflow is organized using `snakemake` so the only step needed to perform the simulation and run the estimation is
```
$ snakemake
```

I installed things with `pip`, and I ran
```
$ cd n_t
$ snakemake
```
And nothing happens:
```

Command 'snakemake' not found, but can be installed with:

sudo apt install snakemake
```

What am I missing?

**Comment by andrewkern** [comment]
Huh seems like snakemake isn’t in your path?

**Comment by agladstein** [comment]
Fixed that by installing in a virtualenv.

`snakemake` ran.

**Comment by andrewkern** [comment]
Nice!
