### ISSUE TITLE
must be `python`

### ISSUE THREAD

**Issue by agladstein** [andrewkern/analysis#5]
I had python 3 installed as `python3`

So, it didn't work as `python`.

Without running in a container with complete control over which python it is, seems like it should be flexible to a `python` or `python3` call.

```
ubuntu@actively-champion-shrimp:~/analysis/n_t$ snakemake
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       simulation
        1       stairwayplot
        3

[Fri Mar  8 00:38:18 2019]
rule simulation:
    output: G3OOA.trees
    jobid: 1

/bin/bash: python: command not found
[Fri Mar  8 00:38:18 2019]
Error in rule simulation:
    jobid: 1
    output: G3OOA.trees

RuleException:
CalledProcessError in line 11 of /home/ubuntu/analysis/n_t/Snakefile:
Command 'set -euo pipefail;  python GutenkunstThreePopOutOfAfrica.py' returned non-zero exit status 127.
  File "/home/ubuntu/analysis/n_t/Snakefile", line 11, in __rule_simulation
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubuntu/analysis/n_t/.snakemake/log/2019-03-08T003818.632251.snakemake.log
```

**Comment by agladstein** [comment]
Although... maybe that wasn't the problem.

I added `alias python=python3` to my `~/.bashrc`, and now `python` works.
But, when I run `snakemake` I'm getting the same error.

This relates back to https://github.com/andrewkern/analysis/issues/2

**Comment by andrewkern** [comment]
think this was a hard coded path issue that should now be fixed. will close this but feel free to reopen when you pull the new version and test it

**Comment by agladstein** [comment]
I'm not entirely sure if that fixed the python3 issue. Now I'm getting a new error. 
I'm going to keep this closed for now, because I think this error has more to do with https://github.com/andrewkern/analysis/issues/2
